### ISSUE TITLE
Problem with 'plurals 0'

### ISSUE THREAD

**Issue by quenenni** [meonkeys/bash-i18n-example#3]
Hello,

Thanks for this nice little script.
Much easier to understand script internalization than when reading some other documentations on the matter.

But there is a problem with your script:
In test.sh, the line 'plurals 0'  print:

```
Here there are 0 oranges
```

'plurals 1' & 'plurals 4' work well.
Apparently, '0' seems to be understood as a plural.. strange isn't it.

Any idea why?

**Comment by quenenni** [comment]
Sorry, I posted a bit too quickly 

In french, I think it's only in singular form (or maybe both singular and plural are ok, not sure)

Can't ngettext manage the special case 0 with a third option?

```
THERE=$(ngettext $"there are no" $"there is" $"there are" $COUNT)
FRUIT=$(ngettext $"orange" $"orange" $"oranges" $COUNT)
```

and with 0 as param, $COUNT isn't printed:

```
Here there are no orange
```

**Comment by quenenni** [comment]
Well...

I discussed with a friend from the Us that told me in english, they say "There are 0 oranges".
So it's good.

But for the french, no-one around me could confirm if we put a 's' or not to 'orange' or if both forms are good.

That's not very important for now so I'm going to continue my script with these rules..

Sorry for the noise.

**Comment by meonkeys** [comment]
No problem, thanks for stopping by. I'd love to add other translations (including French), so if you find anyone who could help with this, please send them on over!

**Comment by quenenni** [comment]
Here is the french translation:

msgid "Hello!"
msgstr "Bonjour!"

msgid "Bye $USER!"
msgstr "Au revoir $USER!"

msgid "Here $THERE $COUNT $FRUIT"
msgstr "Ici $THERE $COUNT $FRUIT"

msgid "there is" 
msgstr "il y a"

msgid "there are"
msgstr "il y a"

msgid "orange" 
msgstr "orange"

msgid "oranges"
msgstr "oranges"

msgid "emptylang"
msgstr "sans langue"

msgid "language set to $L"
msgstr "langage mis à $L"

**Comment by meonkeys** [comment]
@quenenni , Thank you! Will you make a pull request?
